#!/usr/bin/env python3
"""Convert the DeepSeek whale GIF into firmware animation frames.

Reads docs/assets/deepseek-whale.gif (50 frames, transparent bg, blue whale),
samples 16 evenly-spaced frames across one swim cycle, converts each to a
48x48 binary A8 mask (ink-black silhouette on transparent), and writes the
LVGL frame array + a 17th loop-closing duplicate into icons.c / icons.h.
"""
from pathlib import Path
import re

from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
ICONS_C = ROOT / "firmware" / "components" / "ui_app" / "icons.c"
ICONS_H = ROOT / "firmware" / "components" / "ui_app" / "icons.h"
GIF = ROOT / "docs" / "assets" / "deepseek-whale.gif"

SIZE = 48
N_FRAMES = 16
N_TOTAL = N_FRAMES + 1  # + loop-closing duplicate
THRESHOLD = 100         # alpha >= THRESHOLD counts as ink


def load_frames():
    im = Image.open(str(GIF))
    n = getattr(im, "n_frames", 1)
    # sample N_FRAMES evenly; also grab frame 0 for the loop seam
    idxs = [round(i * (n - 1) / (N_FRAMES - 1)) for i in range(N_FRAMES)]
    frames = []
    for i in idxs:
        im.seek(i)
        rgba = im.convert("RGBA")
        frames.append(rgba)
    return frames


def to_mask(frame):
    """Crop to opaque bbox, fit into SIZE x SIZE, threshold to binary."""
    alpha = frame.getchannel("A")
    bbox = alpha.getbbox()
    if not bbox:
        return [0] * (SIZE * SIZE)
    crop = alpha.crop(bbox)
    # fit within SIZE, keep aspect, center
    w, h = crop.size
    scale = min(SIZE / w, SIZE / h)
    nw, nh = max(1, int(w * scale)), max(1, int(h * scale))
    resized = crop.resize((nw, nh), Image.LANCZOS)
    data = [0] * (SIZE * SIZE)
    ox = (SIZE - nw) // 2
    oy = (SIZE - nh) // 2
    px = resized.load()
    for y in range(nh):
        for x in range(nw):
            if px[x, y] >= THRESHOLD:
                data[(oy + y) * SIZE + (ox + x)] = 255
    return data


def emit_frame(index, data):
    values = ",".join(str(v) for v in data)
    return (
        f"static const uint8_t whale_anim_f{index}_map[] = {{{values}}};\n"
        f"const lv_image_dsc_t icon_whale_anim_f{index} = {{\n"
        "  .header = { .magic = LV_IMAGE_HEADER_MAGIC, .cf = LV_COLOR_FORMAT_A8,\n"
        f"               .flags = 0, .w = {SIZE}, .h = {SIZE}, .stride = {SIZE} }},\n"
        f"  .data_size = {SIZE * SIZE}, .data = whale_anim_f{index}_map,\n"
        "};\n"
    )


def main():
    frames = [to_mask(f) for f in load_frames()]
    frames.append(list(frames[0]))  # loop-close
    if any(v not in (0, 255) for frame in frames for v in frame):
        raise SystemExit("generated frames contain non-binary A8 data")

    block_lines = [
        "/* === BEGIN whale animation (generated by scripts/gen_whale_anim.py) === */",
        "",
    ]
    for index, data in enumerate(frames):
        block_lines.append(emit_frame(index, data))
        block_lines.append("")
    block_lines.append(
        "const lv_image_dsc_t *icon_whale_anim[] = {"
        + ", ".join(f"&icon_whale_anim_f{index}" for index in range(N_TOTAL))
        + "};"
    )
    block_lines.append(f"const int icon_whale_anim_count = {N_TOTAL};")
    block_lines.extend(["", "/* === END whale animation === */", ""])
    block = "\n".join(block_lines)

    marker = re.compile(
        r"/\* === BEGIN whale animation.*?=== END whale animation === \*/\n?",
        re.DOTALL,
    )
    c_src = ICONS_C.read_text(encoding="utf-8", errors="replace")
    if marker.search(c_src):
        c_src = marker.sub(block.rstrip("\n"), c_src)
    else:
        c_src = c_src.rstrip() + "\n\n" + block
    ICONS_C.write_text(c_src, encoding="utf-8")

    h_src = ICONS_H.read_text(encoding="utf-8")
    h_decl = (
        "/* whale (deepseek) animation frames (generated) */\n"
        "extern const lv_image_dsc_t *icon_whale_anim[];\n"
        "extern const int icon_whale_anim_count;\n"
    )
    h_marker = re.compile(
        r"/\* whale \(deepseek\) animation frames.*?extern const int icon_whale_anim_count;\n",
        re.DOTALL,
    )
    if h_marker.search(h_src):
        h_src = h_marker.sub(h_decl, h_src)
    else:
        h_src = h_src.rstrip() + "\n" + h_decl
    ICONS_H.write_text(h_src, encoding="utf-8")

    print(f"wrote {N_TOTAL} frames to icons.c / icons.h ({SIZE}x{SIZE} binary A8)")
    f0 = frames[0]
    for i, f in enumerate(frames):
        px_on = sum(1 for v in f if v == 255)
        diff = sum(1 for a, b in zip(f0, f) if a != b)
        print(f"  frame {i:2d}: px={px_on:3d} diff_vs_f0={diff}")


if __name__ == "__main__":
    main()
