#!/usr/bin/env python3
"""Generate 12 hand-drawn/geographic Earth rotation frames for icons.c.

All frames use the new geographic renderer; the legacy icon_earth pixels are
not used. White land is rasterized from Natural Earth country boundaries onto a
fixed black globe. The central meridian advances 120E -> 30E -> 90W, giving the
requested East Asia/Australia -> Europe/Africa -> Americas sequence.
"""
from pathlib import Path
import json
import math
import re
from PIL import Image, ImageDraw
from shapely.geometry import Point, shape
from shapely.ops import unary_union

ROOT = Path(__file__).resolve().parents[1]
ICONS_C = ROOT / "firmware" / "components" / "ui_app" / "icons.c"
ICONS_H = ROOT / "firmware" / "components" / "ui_app" / "icons.h"
DATA = ROOT / "docs" / "preview" / "ne_110m_admin_0_countries.geojson"
SIZE = 48
FRAMES = 12
CX = CY = 24.0
R = 20.0

if not DATA.exists():
    raise SystemExit(f"missing geographic dataset: {DATA}")

geo = json.loads(DATA.read_text(encoding="utf-8"))
land_geoms = [
    shape(f["geometry"])
    for f in geo["features"]
    if f.get("properties", {}).get("CONTINENT") != "Antarctica"
]
LAND = unary_union(land_geoms)


def is_land(lon, lat):
    lon = ((lon + 180.0) % 360.0) - 180.0
    return LAND.covers(Point(lon, lat))


def render(center_lon):
    # A8 alpha=255 is recolored to black by mkicon. Therefore emit black globe
    # pixels everywhere inside the sphere and leave land as transparent white.
    # The outer one-pixel ring is always black, so the limb stays crisp even
    # where a coastline reaches the edge.
    pixels = []
    for y in range(SIZE):
        for x in range(SIZE):
            nx = (x - CX) / R
            ny = (CY - y) / R
            rr = nx * nx + ny * ny
            if rr > 1:
                continue
            radius = math.sqrt((x - CX) ** 2 + (y - CY) ** 2)
            if radius >= R - 1.0:
                pixels.append((x, y))
                continue
            z = math.sqrt(max(0.0, 1.0 - rr))
            view_lon = math.degrees(math.atan2(nx, z))
            lat = math.degrees(math.asin(max(-1.0, min(1.0, ny))))
            if not is_land(center_lon + view_lon, lat):
                pixels.append((x, y))
    return pixels


def emit_frame(idx, pixels):
    data = [0] * (SIZE * SIZE)
    for x, y in pixels:
        data[y * SIZE + x] = 255
    arr = ",".join(str(v) for v in data)
    return (
        f"static const uint8_t earth_anim_f{idx}_map[] = {{{arr}}};\n"
        f"const lv_image_dsc_t icon_earth_anim_f{idx} = {{\n"
        "  .header = { .magic = LV_IMAGE_HEADER_MAGIC, .cf = LV_COLOR_FORMAT_A8,\n"
        f"               .flags = 0, .w = {SIZE}, .h = {SIZE}, .stride = {SIZE} }},\n"
        f"  .data_size = {SIZE * SIZE}, .data = earth_anim_f{idx}_map,\n"
        "};\n"
    )


centers = [120.0 - (360.0 * i / FRAMES) for i in range(FRAMES)]
frames = [render(center) for center in centers]

block_lines = ["/* === BEGIN earth animation (generated by scripts/gen_earth_anim.py) === */", ""]
for i, pixels in enumerate(frames):
    block_lines.append(emit_frame(i, pixels))
    block_lines.append("")
block_lines.append(
    "const lv_image_dsc_t *icon_earth_anim[] = {"
    + ", ".join(f"&icon_earth_anim_f{i}" for i in range(FRAMES))
    + "};"
)
block_lines.append(f"const int icon_earth_anim_count = {FRAMES};")
block_lines.extend(["", "/* === END earth animation === */", ""])
block = "\n".join(block_lines)

c_src = ICONS_C.read_text(encoding="utf-8", errors="replace")
pattern = re.compile(r"/\* === BEGIN earth animation.*?=== END earth animation === \*/\n?", re.DOTALL)
if pattern.search(c_src):
    c_src = pattern.sub(block.rstrip("\n"), c_src)
else:
    c_src = c_src.rstrip() + "\n\n" + block
ICONS_C.write_text(c_src, encoding="utf-8")

h_src = ICONS_H.read_text(encoding="utf-8")
h_decl = (
    "/* earth animation frames (generated) */\n"
    "extern const lv_image_dsc_t *icon_earth_anim[];\n"
    "extern const int icon_earth_anim_count;\n"
)
h_pattern = re.compile(r"/\* earth animation frames.*?extern const int icon_earth_anim_count;\n", re.DOTALL)
if h_pattern.search(h_src):
    h_src = h_pattern.sub(h_decl, h_src)
else:
    h_src = h_src.rstrip() + "\n" + h_decl
ICONS_H.write_text(h_src, encoding="utf-8")

print("generated Earth frames:", FRAMES)
print("center longitudes:", [round(c, 1) for c in centers])
print("white land pixels per frame:", [len(f) for f in frames])
