#!/usr/bin/env python3
"""Generate 12-frame rotate+pulse sun animation A8 data for icons.c.
Uses the REAL icon_sun pixels (extracted from icons.c sun_map[]) so the
style is 100% faithful. Outputs:
  - icons.c append block: sun_anim_frames[] + icon_sun_anim[]
  - icons.h declarations
Idempotent: rewrites only the generated block (between markers)."""
from pathlib import Path
import re, json, math

ROOT = Path(__file__).resolve().parents[1]
ICONS_C = ROOT / "firmware" / "components" / "ui_app" / "icons.c"
ICONS_H = ROOT / "firmware" / "components" / "ui_app" / "icons.h"
CLUSTERS = ROOT / "docs" / "preview" / "sun_clusters.json"
SIZE = 48
FRAMES = 12

# --- load real core + rays ---
data = json.loads(CLUSTERS.read_text())
core = data["core"]["pixels"]
rays = data["rays"]
core_cx, core_cy = data["core"]["centroid"]


def render_frame(ray_translate, ray_rotate_deg, ray_inset=0.0):
    grid = [[0] * SIZE for _ in range(SIZE)]
    # core fixed
    for x, y in core:
        grid[int(y)][int(x)] = 255
    for i, r in enumerate(rays):
        cxr, cyr = r["centroid"]
        rel = r["pixels_rel"]
        bx, by = cxr - core_cx, cyr - core_cy
        # Tighten each ray toward the core along its own axis so the ray root
        # touches the core edge (closes the ~2px gap). Applied before rotation
        # so the inset direction rotates correctly with the ray.
        if ray_inset:
            L = math.hypot(bx, by) or 1
            bx -= bx / L * ray_inset
            by -= by / L * ray_inset
        a = math.radians(ray_rotate_deg)
        rx = bx * math.cos(a) - by * math.sin(a)
        ry = bx * math.sin(a) + by * math.cos(a)
        cosr, sinr = math.cos(a), math.sin(a)
        rot_rel = [(p[0]*cosr - p[1]*sinr, p[0]*sinr + p[1]*cosr) for p in rel]
        tx, ty = ray_translate[i]
        ncx = core_cx + rx + tx
        ncy = core_cy + ry + ty
        for p0, p1 in rot_rel:
            ix, iy = int(round(ncx + p0)), int(round(ncy + p1))
            if 0 <= ix < SIZE and 0 <= iy < SIZE:
                grid[iy][ix] = 255
    # flatten row-major
    return [grid[y][x] for y in range(SIZE) for x in range(SIZE)]


frames_bytes = []
# Discrete rotation: 8 rays only look crisp at 0deg and 45deg (axis-aligned
# cardinal rays vs diagonal rays land on integer pixels). Intermediate angles
# cause sub-pixel placement -> blurry, thinning rays (ON count drops 561->511).
# So rotate by flipping between 0 and 45deg, and let the PULSE (radial translate)
# carry the motion. Pulse uses integer pixel offsets only (round) to stay crisp.
# Loop: FRAMES steps, rotation toggles 0/45 each half, pulse breathes one full
# cosine period. frame[FRAMES] == frame[0] exactly.
for f in range(FRAMES):
    t = f / FRAMES
    breath = 0.5 - 0.5 * math.cos(2 * math.pi * t)   # 0..1..0
    amt = 2.0 * breath
    off = f * (90.0 / FRAMES)            # 90deg = true symmetry period (cardinal<->cardinal); 45deg is NOT symmetric (254px diff)
    trans = []
    for r in rays:
        cxr, cyr = r["centroid"]
        dx, dy = cxr - core_cx, cyr - core_cy
        L = math.hypot(dx, dy) or 1
        # integer pixel translate to keep rays crisp
        trans.append((round(dx / L * amt), round(dy / L * amt)))
    frames_bytes.append(render_frame(trans, off, ray_inset=2.0))

def count_on(bts):
    return sum(1 for v in bts if v > 0)
print(f"frame0 ON={count_on(frames_bytes[0])}, frame{FRAMES-1} ON={count_on(frames_bytes[-1])}")
ons = [count_on(b) for b in frames_bytes]
print("per-frame ON:", ons)

# seam check: re-render frame at t=1.0 (== frame[12]) and compare to frame[0]
amt = 2.0 * (0.5 - 0.5 * math.cos(2 * math.pi * 1.0))  # == 0
trans = []
for r in rays:
    cxr, cyr = r["centroid"]
    dx, dy = cxr - core_cx, cyr - core_cy
    L = math.hypot(dx, dy) or 1
    trans.append((round(dx / L * amt), round(dy / L * amt)))
f12 = render_frame(trans, 90.0, ray_inset=2.0)
seam_diff = sum(1 for a, b in zip(frames_bytes[0], f12) if (a > 0) != (b > 0))
print(f"seam frame[0] vs frame[12]: {seam_diff} pixels differ")

# --- build C source ---
def emit_frame(idx, bts):
    arr = ",".join(str(v) for v in bts)
    return (f"static const uint8_t sun_anim_f{idx}_map[] = {{{arr}}};\n"
            f"const lv_image_dsc_t icon_sun_anim_f{idx} = {{\n"
            f"  .header = {{ .magic = LV_IMAGE_HEADER_MAGIC, .cf = LV_COLOR_FORMAT_A8,\n"
            f"               .flags = 0, .w = {SIZE}, .h = {SIZE}, .stride = {SIZE} }},\n"
            f"  .data_size = {SIZE*SIZE}, .data = sun_anim_f{idx}_map,\n}};\n")

block_lines = [
    "/* === BEGIN sun animation (generated by scripts/gen_sun_anim.py) === */",
    "",
]
for i, bts in enumerate(frames_bytes):
    block_lines.append(emit_frame(i, bts))
    block_lines.append("")

# array of pointers
ptr_arr = "const lv_image_dsc_t *icon_sun_anim[] = {" + ", ".join(f"&icon_sun_anim_f{i}" for i in range(FRAMES)) + "};"
block_lines.append(ptr_arr)
block_lines.append(f"const int icon_sun_anim_count = {FRAMES};")
block_lines.append("")
block_lines.append("/* === END sun animation === */")
block_lines.append("")
block = "\n".join(block_lines)

# --- splice into icons.c (replace between markers, or append before EOF) ---
c_src = ICONS_C.read_text(encoding="utf-8", errors="replace")
pattern = re.compile(r"/\* === BEGIN sun animation.*?=== END sun animation === \*/\n?", re.DOTALL)
if pattern.search(c_src):
    c_src = pattern.sub(block.rstrip("\n"), c_src)
else:
    c_src = c_src.rstrip() + "\n\n" + block
ICONS_C.write_text(c_src, encoding="utf-8")

# --- splice into icons.h ---
h_src = ICONS_H.read_text(encoding="utf-8")
h_decl = (
    "/* sun animation frames (generated) */\n"
    f"extern const lv_image_dsc_t *icon_sun_anim[];\n"
    f"extern const int icon_sun_anim_count;\n"
)
h_pat = re.compile(r"/\* sun animation frames.*?extern const int icon_sun_anim_count;\n", re.DOTALL)
if h_pat.search(h_src):
    h_src = h_pat.sub(h_decl, h_src)
else:
    h_src = h_src.rstrip() + "\n" + h_decl
ICONS_H.write_text(h_src, encoding="utf-8")

print(f"wrote {FRAMES} frames to icons.c / icons.h ({SIZE}x{SIZE} A8 each, {SIZE*SIZE} bytes/frame)")
